#:schema node_modules/wrangler/config-schema.json
name = "dns123"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "46e48961e23144dcab32e08f3cdd1813" }
]

[assets]
directory = "./public"
